# """
# Install Fedora (recommended).
# Updated 2020-11-12.
# """

FROM acidgenomics/fedora:33-minimal
MAINTAINER docker@acidgenomics.com

RUN /usr/local/koopa/os/linux/sbin/configure-vm --recommended --verbose
