# """
# Install Fedora (recommended).
# Updated 2020-11-06.
# """

FROM acidgenomics/fedora:33-minimal
MAINTAINER docker@acidgenomics.com

ARG TERM=xterm-256color

RUN /usr/local/koopa/os/linux/sbin/configure-vm --verbose
