# > install.packages("BiocManager")
library(BiocManager)
# > install(
# >     update = TRUE,
# >     ask = FALSE,
# >     version = Sys.getenv("BIOC_VERSION")
# > )
install(
    pkgs = c(
        "AnnotationDbi",
        "AnnotationHub",
        "Biobase",
        "BiocCheck",
        "BiocGenerics",
        "BiocParallel",
        "BiocStyle",
        "Biostrings",
        "DT",
        "DelayedArray",
        "GSEABase",
        "GenomeInfoDb",
        "GenomeInfoDbData",
        "GenomicAlignments",
        "GenomicFeatures",
        "GenomicRanges",
        "IRanges",
        "Matrix",
        "Matrix.utils",
        "R.utils",
        "S4Vectors",
        "SingleCellExperiment",
        "SummarizedExperiment",
        "backports",
        "covr",
        "cowplot",
        "curl",
        "devtools",
        "ensembldb",
        "ggrepel",
        "knitr",
        "lintr",
        "magrittr",
        "patrick",
        "pbapply",
        "rcmdcheck",
        "remotes",
        "reticulate",
        "rlang",
        "rmarkdown",
        "roxygen2",
        "rtracklayer",
        "sessioninfo",
        "testthat",
        "tidyverse",
        "viridis",
        "xmlparsedata"
    ),
    update = TRUE,
    ask = FALSE
)
