# """
# AWS Batch single-cell RNA-seq image.
# Updated 2020-05-06.
# """

FROM acidgenomics/singlecell:latest
MAINTAINER mike@steinbaugh.com

ENTRYPOINT ["/usr/local/koopa/bin/aws-batch-fetch-and-run"]
