# """
# Install CentOS (recommended).
# Updated 2020-11-12.
# """

FROM acidgenomics/centos:8-minimal
MAINTAINER docker@acidgenomics.com

RUN /opt/koopa/os/linux/common/sbin/configure-vm --recommended --verbose
