# """
# Install Biocontainers (recommended).
# Updated 2020-08-07.
# """

FROM biocontainers/biocontainers:latest
MAINTAINER mike@steinbaugh.com

WORKDIR /tmp
ADD install.sh .
RUN ./install.sh
WORKDIR /
