# """
# bcbio-nextgen RNA-seq pipeline.
# Updated 2020-09-22.
# """

FROM quay.io/bcbio/bcbio-vc:1.2.4-9722272
MAINTAINER mike@steinbaugh.com

WORKDIR /tmp
ADD install.sh .
RUN ./install.sh
WORKDIR /
