# """
# AWS Batch Nextflow MNase-seq image.
# Updated 2020-05-06.
# """

FROM acidgenomics/nextflow-mnaseseq:latest
MAINTAINER mike@steinbaugh.com

ENTRYPOINT ["/usr/local/koopa/bin/aws-batch-fetch-and-run"]
