# """
# AWS Batch Nextflow nascent RNA image.
# Updated 2020-05-06.
# """

FROM acidgenomics/nextflow-nascent:latest
MAINTAINER mike@steinbaugh.com

ENTRYPOINT ["/usr/local/koopa/bin/aws-batch-fetch-and-run"]
