# """
# Install Bioconductor release.
# Updated 2020-11-06.
# """

FROM acidgenomics/debian:minimal
MAINTAINER docker@acidgenomics.com

RUN /usr/local/koopa/os/linux/sbin/configure-vm --bioconductor --verbose
