# """
# AWS Batch Nextflow scRNA-seq image.
# Updated 2020-05-06.
# """

FROM acidgenomics/nextflow-scrnaseq:latest
MAINTAINER mike@steinbaugh.com

ENTRYPOINT ["/usr/local/koopa/bin/aws-batch-fetch-and-run"]
