# """
# AWS Batch Nextflow RNA fusion detection image.
# Updated 2020-05-06.
# """

FROM acidgenomics/nextflow-rnafusion:latest
MAINTAINER mike@steinbaugh.com

ENTRYPOINT ["/usr/local/koopa/bin/aws-batch-fetch-and-run"]
