library(remotes)
Sys.setenv("R_REMOTES_UPGRADE" = "always")
install_github("acidgenomics/acidtest")
install_github("acidgenomics/bioverbs")
install_github("acidgenomics/goalie")
install_github("acidgenomics/transformer")
install_github("acidgenomics/syntactic")
install_github("acidgenomics/brio")
install_github("acidgenomics/freerange")
install_github("acidgenomics/basejump")
install_github("acidgenomics/minimalism")
install_github("acidgenomics/firestarter")
update_packages()
