library(remotes)
Sys.setenv("R_REMOTES_UPGRADE" = "always")
install_github("acidgenomics/acidtest", dependencies = TRUE)
install_github("acidgenomics/bioverbs", dependencies = TRUE)
install_github("acidgenomics/goalie", dependencies = TRUE)
install_github("acidgenomics/transformer", dependencies = TRUE)
install_github("acidgenomics/syntactic", dependencies = TRUE)
install_github("acidgenomics/brio", dependencies = TRUE)
install_github("acidgenomics/freerange", dependencies = TRUE)
install_github("acidgenomics/basejump", dependencies = TRUE)
install_github("acidgenomics/acidplots", dependencies = TRUE)
update_packages()
