library(remotes)
Sys.setenv("R_REMOTES_UPGRADE" = "always")
install_github(repo = "acidgenomics/acidtest", dependencies = TRUE)
install_github(repo = "acidgenomics/bioverbs", dependencies = TRUE)
install_github(repo = "acidgenomics/goalie", dependencies = TRUE)
install_github(repo = "acidgenomics/transformer", dependencies = TRUE)
install_github(repo = "acidgenomics/syntactic", dependencies = TRUE)
install_github(repo = "acidgenomics/brio", dependencies = TRUE)
install_github(repo = "acidgenomics/freerange", dependencies = TRUE)
install_github(repo = "acidgenomics/basejump", dependencies = TRUE)
install_github(repo = "acidgenomics/acidplots", dependencies = TRUE)
update_packages(ask = FALSE)
