# """
# Install Biocontainers (minimal).
# Updated 2020-08-07.
# """

FROM biocontainers/biocontainers:latest
MAINTAINER docker@acidgenomics.com

RUN curl -sSL https://koopa.acidgenomics.com/install \
        | bash -s -- --non-interactive --test
