# """
# Install Debian (recommended).
# Updated 2021-02-15.
# """

FROM acidgenomics/debian:10-minimal
MAINTAINER docker@acidgenomics.com

RUN /opt/koopa/os/linux/common/sbin/configure-vm --recommended --verbose
