# """
# Install Ubuntu 20.04 LTS (recommended).
# Updated 2020-11-12.
# """

FROM acidgenomics/ubuntu:20.04-minimal
MAINTAINER docker@acidgenomics.com

RUN /opt/koopa/os/linux/common/sbin/configure-vm --recommended --verbose
